FROM golang:1.8.3-alpine

ARG APP_VERSION=unkown

ADD . /go/src/github.com/harishanchu/kube-db-backup

WORKDIR /go/src/github.com/harishanchu/kube-db-backup

RUN mkdir -p /dist
RUN go build -ldflags "-X main.version=$APP_VERSION" -o /dist/mgob github.com/harishanchu/kube-db-backup

CMD ["ls"]